# Generated by Django 4.2.3 on 2023-07-30 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='usertype',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
