# Generated by Django 4.2.3 on 2023-07-30 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_users_usertype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='phone_number',
            new_name='phone',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='usertype',
            new_name='type',
        ),
    ]
