# Generated by Django 4.2.3 on 2023-07-30 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_phone_number_users_phone_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='user_id',
            new_name='userid',
        ),
    ]
