# Generated by Django 4.2.3 on 2023-07-30 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_user_id_users_userid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='type',
            new_name='usertype',
        ),
    ]
