# Generated by Django 4.2.3 on 2023-07-30 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_type_users_usertype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='userid',
            new_name='uid',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='usertype',
            new_name='user_type',
        ),
    ]
