# Generated by Django 4.2.3 on 2023-07-30 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_userid_users_uid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='phone',
            new_name='phonenumber',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='user_type',
            new_name='typeofuser',
        ),
    ]
