# Generated by Django 4.2.3 on 2023-07-30 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_phone_users_phonenumber_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='phonenumber',
            new_name='phnumber',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='typeofuser',
            new_name='typeuser',
        ),
    ]
