# Generated by Django 4.2.3 on 2023-07-30 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_rename_phonenumber_users_phnumber_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='phnumber',
            new_name='phone',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='typeuser',
            new_name='users',
        ),
    ]
