# Generated by Django 4.2.3 on 2023-07-30 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_rename_phnumber_users_phone_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='users',
            new_name='type',
        ),
    ]
