# Generated by Django 4.2.3 on 2023-07-30 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_users_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='phone',
            new_name='phone_number',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='password',
            new_name='pssword',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='uid',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='type',
            new_name='usertype',
        ),
    ]
