# Generated by Django 3.2.20 on 2023-08-09 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20230807_2330'),
    ]

    operations = [
        migrations.CreateModel(
            name='File1_log',
            fields=[
                ('file_id', models.UUIDField()),
                ('data', models.BinaryField(blank=True, null=True)),
                ('file_version_id', models.UUIDField()),
                ('fileserver1_id', models.AutoField(primary_key=True, serialize=False)),
                ('secret', models.BinaryField()),
                ('delete_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'file1_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='File2_log',
            fields=[
                ('file_id', models.UUIDField()),
                ('data', models.BinaryField(blank=True, null=True)),
                ('file_version_id', models.UUIDField()),
                ('fileserver2_id', models.AutoField(primary_key=True, serialize=False)),
                ('secret', models.BinaryField()),
                ('delete_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'file2_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='File3_log',
            fields=[
                ('file_id', models.UUIDField()),
                ('data', models.BinaryField(blank=True, null=True)),
                ('file_version_id', models.UUIDField()),
                ('fileserver3_id', models.AutoField(primary_key=True, serialize=False)),
                ('secret', models.BinaryField()),
                ('delete_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'file3_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='File4_log',
            fields=[
                ('file_id', models.UUIDField()),
                ('data', models.BinaryField(blank=True, null=True)),
                ('file_version_id', models.UUIDField()),
                ('fileserver4_id', models.AutoField(primary_key=True, serialize=False)),
                ('secret', models.BinaryField()),
                ('delete_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'file4_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='File5_log',
            fields=[
                ('file_id', models.UUIDField()),
                ('data', models.BinaryField(blank=True, null=True)),
                ('file_version_id', models.UUIDField()),
                ('fileserver5_id', models.AutoField(primary_key=True, serialize=False)),
                ('secret', models.BinaryField()),
                ('delete_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'file5_log',
                'managed': False,
            },
        ),
        migrations.AlterModelTable(
            name='file1',
            table='file1',
        ),
        migrations.AlterModelTable(
            name='file2',
            table='file2',
        ),
        migrations.AlterModelTable(
            name='file3',
            table='file3',
        ),
        migrations.AlterModelTable(
            name='file4',
            table='file4',
        ),
    ]
