# Generated by Django 4.2.3 on 2023-07-26 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceLog',
            fields=[
                ('invoice_id', models.AutoField(primary_key=True, serialize=False)),
                ('subscriptiontype', models.CharField(blank=True, max_length=50, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('client_id', models.IntegerField(blank=True, null=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('pay_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'invoice_log',
                'managed': False,
            },
        ),
    ]
