# Generated by Django 4.1.4 on 2023-07-27 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_invoicelog"),
    ]

    operations = [
        migrations.CreateModel(
            name="File",
            fields=[
                ("file_id", models.UUIDField()),
                ("data", models.BinaryField(blank=True, null=True)),
                ("file_version_id", models.UUIDField()),
                ("fileserver1_id", models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                "db_table": "file",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Secret",
            fields=[
                (
                    "secret",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("file_id", models.UUIDField(blank=True, null=True)),
            ],
            options={
                "db_table": "secret",
                "managed": False,
            },
        ),
    ]
