# Generated by Django 3.2.20 on 2023-08-07 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_file_secret'),
    ]

    operations = [
        migrations.CreateModel(
            name='File1',
            fields=[
                ('file_id', models.UUIDField()),
                ('data', models.BinaryField(blank=True, null=True)),
                ('file_version_id', models.UUIDField()),
                ('fileserver1_id', models.AutoField(primary_key=True, serialize=False)),
                ('secret', models.BinaryField()),
            ],
            options={
                'db_table': 'file',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='File2',
            fields=[
                ('file_id', models.UUIDField()),
                ('data', models.BinaryField(blank=True, null=True)),
                ('file_version_id', models.UUIDField()),
                ('fileserver2_id', models.AutoField(primary_key=True, serialize=False)),
                ('secret', models.BinaryField()),
            ],
            options={
                'db_table': 'file',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='File3',
            fields=[
                ('file_id', models.UUIDField()),
                ('data', models.BinaryField(blank=True, null=True)),
                ('file_version_id', models.UUIDField()),
                ('fileserver3_id', models.AutoField(primary_key=True, serialize=False)),
                ('secret', models.BinaryField()),
            ],
            options={
                'db_table': 'file',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='File4',
            fields=[
                ('file_id', models.UUIDField()),
                ('data', models.BinaryField(blank=True, null=True)),
                ('file_version_id', models.UUIDField()),
                ('fileserver4_id', models.AutoField(primary_key=True, serialize=False)),
                ('secret', models.BinaryField()),
            ],
            options={
                'db_table': 'file',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='File5',
            fields=[
                ('fileserver5_id', models.AutoField(primary_key=True, serialize=False)),
                ('file_version_id', models.UUIDField()),
                ('file_id', models.UUIDField()),
                ('data', models.BinaryField(blank=True, editable=True, null=True)),
                ('secret', models.BinaryField(editable=True)),
            ],
            options={
                'db_table': 'file5',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Secret2',
            fields=[
                ('secret', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('file_id', models.UUIDField(blank=True, null=True)),
            ],
            options={
                'db_table': 'secret',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='File',
        ),
    ]
